apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: loki-datasource
  namespace: grafana-operator
spec:
  name: loki-datasource
  datasources:
  - name: loki
    type: loki
    url: http://loki.loki:3100
    isDefault: false