apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: loki-datasource
  namespace: grafana-operator
spec:
  name: loki-datasource
  datasources:
  - name: loki
    type: loki
    uid: loki
    url: http://loki.loki:3100
    isDefault: false
    jsonData:
      derivedFields:
      - name: trace_id
        matcherRegex: 'trace_id\":\"(\w+)\"'
        url: '$${__value.raw}'
        datasourceUid: tempo