apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: tempo-datasource
  namespace: grafana-operator
spec:
  name: tempo-datasource
  datasources:
    - name: tempo
      type: tempo
      url: http://tempo.tempo:3100
      isDefault: false
