globalArguments: ["--providers.kubernetesingress.ingressendpoint.hostname=localhost"]
logs:
  general:
    format: json
    level: INFO
service:
  type: NodePort
tracing:
  jaeger:
    localAgentHostPort: tempo.tempo:6831
ports:
  web:
    nodePort: 30000
  websecure:
    nodePort: 30001
