globalArguments: ["--providers.kubernetesingress.ingressendpoint.hostname=localhost"]
logs:
  general:
    format: json
    level: INFO
service:
  type: NodePort
ports:
  web:
    nodePort: 30000
  websecure:
    nodePort: 30001
