apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_datasource: ""
  name: grafana-datasources
  namespace: grafana
data:
  tempo.yaml: |
    apiVersion: 1
    datasources:
    - jsonData:
        tracesToLogs:
          datasourceUid: loki
          mappedTags: [{ key: 'service.name', value: 'app' }]
          mapTagNamesEnabled: true
          filterByTraceID: true
      name: tempo
      type: tempo
      uid: tempo
      url: http://tempo.tempo:3100
  loki.yaml: |
    apiVersion: 1
    datasources:
    - jsonData:
        derivedFields:
        - datasourceUid: tempo
          matcherRegex: trace_id\":\"(\w+)\"
          name: trace_id
          url: $${__value.raw}
      name: loki
      type: loki
      uid: loki
      url: http://loki.loki:3100
  prometheus.yaml: |
    apiVersion: 1
    datasources:
    - isDefault: true
      name: prometheus
      type: prometheus
      uid: prometheus
      url: http://prometheus-server.prometheus
