envFromSecret: grafana-github
env:
  GF_FEATURE_TOGGLES_ENABLE: flameGraph
ingress:
  enabled: true
sidecar:
  datasources:
    enabled: true
    searchNamespace: observability
    initDatasources: true
  dashboards:
    enabled: true
    labelValue: "1"
    searchNamespace: ALL
grafana.ini:
  users:
    auto_assign_org_role: Viewer
  log:
    level: debug
  auth:
    disable_login_form: true
    disable_signout_menu: true
  auth.github:
    enabled: true
    client_id: ${AUTH_GITHUB_CLIENT_ID}
    client_secret: ${AUTH_GITHUB_CLIENT_SECRET}
    scopes: user:email,read:org
    auth_url: https://github.com/login/oauth/authorize
    token_url: https://github.com/login/oauth/access_token
    api_url: https://api.github.com/user
    allowed_organizations: devops-syndicate
    role_attribute_path: contains(groups[*], '@devops-syndicate/admins') && 'Admin' || 'Editor'
