apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_datasource: ""
  name: loki-datasource
  namespace: observability
data:
  loki.yaml: |
    apiVersion: 1
    datasources:
    - jsonData:
        timeout: 60
        maxLines: 1000
        derivedFields:
        - datasourceUid: tempo
          matcherRegex: trace_id\":\"(\w+)\"
          name: trace_id
          url: $${__value.raw}
      access: proxy
      name: loki
      type: loki
      uid: loki
      url: http://loki.observability:3100
