apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_datasource: ""
  name: mimir-datasource
  namespace: grafana
data:
  mimir.yaml: |
    apiVersion: 1
    datasources:
    - isDefault: true
      name: mimir
      type: prometheus
      uid: mimir
      url: http://mimir-nginx.mimir:80/prometheus