apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_datasource: ""
  name: prometheus-datasource
  namespace: grafana
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
    - isDefault: true
      name: prometheus
      type: prometheus
      uid: prometheus
      url: http://prometheus-server.prometheus