apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_datasource: ""
  name: prometheus-datasource
  namespace: observability
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
    - name: prometheus
      type: prometheus
      uid: prometheus
      url: http://prometheus-server.observability
