apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_datasource: ""
  name: pyroscope-datasource
  namespace: observability 
data:
  pyroscope.yaml: |
    apiVersion: 1
    datasources:
    - name: pyroscope
      type: grafana-pyroscope-datasource
      uid: pyroscope
      url: http://pyroscope.observability:4040
