apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xpostgresqlinstances.database.devopssyndicate.github.io
spec:
  group: database.devopssyndicate.github.io
  names:
    kind: XPostgreSQLInstance
    plural: xpostgresqlinstances
  defaultCompositionRef:
    name: xpostgresqlinstances.aws.database.devopssyndicate.github.io
  claimNames:
    kind: PostgreSQLInstance
    plural: postgresqlinstances
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  storageGB:
                    type: integer
                  passwordSecretRef:
                    type: object
                    properties:
                      key:
                        type: string
                      name:
                        type: string
                      namespace:
                        type: string
                    required:
                    - key
                    - name
                    - namespace
                required:
                - storageGB
                - passwordSecretRef
            required:
            - parameters
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xpostgresqlinstances.aws.database.devopssyndicate.github.io
  labels:
    provider: aws
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: database.devopssyndicate.github.io/v1alpha1
    kind: XPostgreSQLInstance
  resources:
  - name: rdsinstance
    base:
      apiVersion: rds.aws.upbound.io/v1beta1
      kind: Instance
      spec:
        forProvider:
          autoGeneratePassword: true
          engine: postgres
          engineVersion: "14.7"
          instanceClass: db.t3.micro
          region: eu-central-1
          skipFinalSnapshot: true
          username: adminuser
        writeConnectionSecretToRef:
          namespace: crossplane-system
    patches:
    - fromFieldPath: "metadata.uid"
      toFieldPath: "spec.writeConnectionSecretToRef.name"
      transforms:
      - type: string
        string:
          fmt: "%s-db"
    - fromFieldPath: "spec.parameters.storageGB"
      toFieldPath: "spec.forProvider.allocatedStorage"
    - fromFieldPath: "spec.parameters.passwordSecretRef"
      toFieldPath: "spec.forProvider.passwordSecretRef"