server:
  ingress:
    enabled: true
  extraArgs:
  - --insecure
controller:
  args:
    appResyncPeriod: 30
configs:
  secret:
    argocdServerAdminPassword: "$2a$10$uFpv5.xxyayOJP0gjG1W4O3dwk9aUv/0pL./uyR3R8uwrvCDAzgPy"
    argocdServerAdminPasswordMtime: "2022-06-02T18:44:00Z"
